language: node_js
node_js:
  - 19

services:
  - docker

before_install:
  - docker build -t my-docker-app:latest .

script:
  - docker run my-docker-app:latest npm test
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push my-docker-app:latest

deploy:
  provider: script
  script: docker run -d -p 3000:3000 my-docker-app:latest
  on:
    branch: main
